// Generate the real proofs the LiteSVM tests run against, with the pinned ceremony artifacts.
//
//   npm run fixtures            (after `npm run fetch` in ../artifacts)
//
// Writes ../program/tests-litesvm/fixtures/proofs.json. The file is committed so `cargo test`
// needs nothing but Rust; this script is what proves the file was not written by hand.

import { createHash } from 'node:crypto'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { Identity } from '@semaphore-protocol/identity'

import { commitmentOf } from '../src/code.ts'
import { toBytes32 } from '../src/field.ts'
import { proveMembership } from '../src/proof.ts'
import { MESSAGE_NS, SCOPE_NS } from '../src/field.ts'

const here = dirname(fileURLToPath(import.meta.url))
const artifactDir = join(here, '../../artifacts')
const outPath = join(here, '../../program/tests-litesvm/fixtures/proofs.json')
const artifacts = {
  wasm: join(artifactDir, 'semaphore-32.wasm'),
  zkey: join(artifactDir, 'semaphore-32.zkey'),
}

const hex = (b: Uint8Array) => Buffer.from(b).toString('hex')
const sha256File = (p: string) => createHash('sha256').update(readFileSync(p)).digest('hex')

// Alice's secret is the one `keys/test/vectors.json` pins, so the fixtures run the whole chain
// from the keys recipe through to a verified proof. The others are plain bytes.
const secrets = {
  alice: Buffer.from('54684ed3bd15671b1a07bd8ed840a049c60ce847afd7d8da73b4f71cc6884d85', 'hex'),
  bob: Buffer.from('forest registry fixture: bob'),
  carol: Buffer.from('forest registry fixture: carol'),
}
const dids = {
  alice: 'did:plc:wece24yzukt4pj6hqvmb2fn4',
  bob: 'did:plc:jhlp4q2nzhrz5timu2qxe4ln',
  carol: 'did:plc:ewvi7nxzyoun6zhxrhs64oiz',
}

// Two markets from the directory's first example, and one more so a proof can be presented
// against the wrong name.
const markets = { tutors: 'online-tutors', cleaning: 'house-cleaning' }

// List 0 holds Alice and Bob with two strangers between them, so nobody is at index 0 or the end
// and the Merkle paths are not all the same shape. List 1 holds Carol, opened later.
const filler = (n: number) => new Identity(Buffer.from(`forest registry fixture: filler ${n}`))
const list0 = [
  commitmentOf(filler(1)),
  commitmentOf(secrets.alice),
  commitmentOf(filler(2)),
  commitmentOf(filler(3)),
  commitmentOf(secrets.bob),
]
const list1 = [commitmentOf(filler(4)), commitmentOf(secrets.carol), commitmentOf(filler(5))]
// Enough to push a root all the way out of a 128-slot ring, and one short of it.
const extra = Array.from({ length: 128 }, (_, i) => commitmentOf(filler(100 + i)))

const cases = [
  { name: 'alice-tutors', listIndex: 0, leaves: list0, secret: secrets.alice, did: dids.alice, market: markets.tutors },
  { name: 'alice-cleaning', listIndex: 0, leaves: list0, secret: secrets.alice, did: dids.alice, market: markets.cleaning },
  { name: 'bob-tutors', listIndex: 0, leaves: list0, secret: secrets.bob, did: dids.bob, market: markets.tutors },
  { name: 'bob-cleaning', listIndex: 0, leaves: list0, secret: secrets.bob, did: dids.bob, market: markets.cleaning },
  { name: 'carol-tutors-list1', listIndex: 1, leaves: list1, secret: secrets.carol, did: dids.carol, market: markets.tutors },
]

const proofs = []
for (const c of cases) {
  const t0 = performance.now()
  const p = await proveMembership({
    secret: c.secret,
    market: c.market,
    did: c.did,
    leaves: c.leaves,
    artifacts,
  })
  console.log(`${c.name}: ${Math.round(performance.now() - t0)} ms, code ${p.code}`)
  proofs.push({
    name: c.name,
    listIndex: c.listIndex,
    market: c.market,
    did: c.did,
    root: hex(toBytes32(p.root)),
    code: hex(toBytes32(p.code)),
    scope: hex(toBytes32(p.scope)),
    message: hex(toBytes32(p.message)),
    a: hex(p.proof.a),
    b: hex(p.proof.b),
    c: hex(p.proof.c),
    // snarkjs's own points, so the Rust side can check that decompressing what the client wrote
    // gives back exactly these.
    uncompressed: {
      a: hex(Buffer.concat([toBytes32(BigInt(p.raw.pi_a[0])), toBytes32(BigInt(p.raw.pi_a[1]))])),
      b: hex(
        Buffer.concat([
          toBytes32(BigInt(p.raw.pi_b[0][1])),
          toBytes32(BigInt(p.raw.pi_b[0][0])),
          toBytes32(BigInt(p.raw.pi_b[1][1])),
          toBytes32(BigInt(p.raw.pi_b[1][0])),
        ]),
      ),
      c: hex(Buffer.concat([toBytes32(BigInt(p.raw.pi_c[0])), toBytes32(BigInt(p.raw.pi_c[1]))])),
    },
  })
}

const out = {
  note: 'Generated by registry/client/scripts/fixtures.ts. Real proofs, real ceremony artifacts.',
  artifacts: {
    ceremony: 'Semaphore 4.0.0, the public July 2024 ceremony',
    depth: 32,
    zkeySha256: sha256File(artifacts.zkey),
    wasmSha256: sha256File(artifacts.wasm),
  },
  scopeNamespace: SCOPE_NS,
  messageNamespace: MESSAGE_NS,
  lists: [
    { index: 0, leaves: list0.map(String) },
    { index: 1, leaves: list1.map(String) },
  ],
  extraLeaves: extra.map(String),
  proofs,
}

mkdirSync(dirname(outPath), { recursive: true })
writeFileSync(outPath, JSON.stringify(out, null, 1) + '\n')
console.log(`wrote ${outPath}`)
process.exit(0)
